name: Joke Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  joke:
    name: Tell me a joke
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run joker.py
        run: python joker.py

      - name: Add, commit, and push
        uses: actions4git/add-commit-push@v1.0.0
        with:
          path: .
          commit-message: "Automated changes"
          push-force: false
